### ISSUE TITLE
Naming of std libraries

### ISSUE THREAD

**Issue by peterbud** [tschoonj/GTK-for-Windows-Runtime-Environment-Installer#5]
Tom, first this is an excellent and useful package.

Compiling GTK apps under MSYS2 whowever I have noticed that there are 3 libraries in this package, where the naming convention causes issues:
- The package contains libgcc_s_seh**_64**-1.dll, however copiled apps are looking for libgcc_s_seh-1.dll
- The package contains libstdc++**_64**-6.dll, however copiled apps are looking for libstdc++-6.dll
- The package contains libwinpthread**_64**-1.dll, however copiled apps are looking for libwinpthread-1.dll

Is this intentional that the "_64" suffix is added to file names? I don't see this suffix in any other GTK libraries.

**Comment by tschoonj** [comment]
Hi Peter,

The reason for this is that I am using the [TDM-GCC's compiler](http://tdm-gcc.tdragon.net) package, which is not identical to the one that ships with MSYS2. As you noticed yourself, there is indeed a naming convention difference between both: the libraries with the **_64** are the ones that ship with TDM-GCC and I have no control over their naming convention.

This is why I recommend that everybody who wants to compile code against the libraries I distribute in the installer, downloads the SDK I provide as well as installs the TDM-GCC compiler distribution.

This being said, for the next release, I may switch to using MSYS2 as I no longer have the time to compile all these libraries from scratch (it takes me about two days to generate a new release) and more importantly because the current TDM-GCC release (about 14 months old) is rather buggy and there is no new release in sight.

Hope this helps!

Tom

**Comment by peterbud** [comment]
Hi Tom,
 
sounds really good. I can even help to create the MSYS2 version. We just need to replace the appropriate libraries from the MSYS2 package, right?

Peter

**Comment by tschoonj** [comment]
Yep, all the files in the subfolders of gtk-nsis-pack would need to be replaced with the ones provided by MSYS2, and both gtk2-runtime.nsi and gtk3-runtime.nsi would need to be updated to reflect the new libraries.

If you would file a PR with those changes, I could easily produce a new installer and do a bit of testing to ensure everything still works fine.
